version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.docker
    ports:
      - "8000:80"
    volumes_from:
      - app
    links:
      - app
  ui:
    build:
      context: ./
      dockerfile: ui.docker
    ports:
      - "80:5000"
    volumes:
      - ./frontend:/var/www
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./backend:/var/www
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
  db:
    image: mysql:5.6
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=todo-app"
    ports:
      - "33061:3306"
